name: Syncity
version: '${version}'
main: me.drwoops.syncity.Syncity
api-version: 1.18
authors: [ drwoops ]
description: a paper plugin to sync all the things when players move between servers
website: https://github.com/drwoops/syncity
commands:
  syncity:
    description: execute a syncity command
    usage: /<command> subcommand args...
